version: 2.1

jobs:
  build:
    macos:
      xcode: "15.0.0"  # Usa una versión compatible con tu proyecto
    working_directory: /Users/distiller/project
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout  # Clona el código desde GitHub

      - run:
          name: Crear directorios
          command: mkdir -p output/

      - run:
          name: Instalar dependencias
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3

      - run:
          name: Compilar y generar .ipa
          command: |
            set -o pipefail && xcodebuild -workspace TuApp.xcworkspace \
              -scheme TuEsquema \
              -sdk iphoneos \
              -configuration Release \
              -archivePath output/App.xcarchive archive \
              CODE_SIGNING_ALLOWED=NO | tee output/build.log

            set -o pipefail && xcodebuild -exportArchive \
              -archivePath output/App.xcarchive \
              -exportOptionsPlist exportOptions.plist \
              -exportPath output/ | tee output/export.log

      - store_artifacts:
          path: output/
